title: Nathan Gray
url: "https://nathantgray.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/nathantgray"
# footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

#nav:
# - name: "plotly"
#   link: "ieee_loss_min_inverters_1035pu.html"
# - name: "Resume"
#   link: "resume.pdf"
# - name: "Contact"
#   link: "contact"
