title: Nathan Gray
url: "https://nathantgray.github.io"
baseurl: "/"

theme: minima
markdown: Pandoc  # kramdown
#ins_logo: "./bits-logo.png"

plugins:
  - jekyll-feed
  - jekyll-spaceship
pandoc:
  extensions:
    - csl: assets/bib/style/apa.csl
    - bibliography: assets/bib/library.bib
    - filter: mermaid-filter
    - filter: mathjax-pandoc-filter
    - '-Mmathjax.centerDisplayMath' # center display math

footer: yes
footer_url: "https://github.com/nathantgray"
footer_text: "source"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "PDF"
   link: "cv_nathan_gray.pdf"
   new_tab: true
# - name: "Contact"
#   link: "contact"

# Where things are
jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor